### ISSUE TITLE
Port library for esp8266 and esp32

### ISSUE THREAD

**Issue by akshaythoke9116** [board707/DMD_STM32#13]
Hello,
I want to use esp8266 and esp32 for monochrome display. please port or tell me how to port the library to esp

**Comment by board707** [comment]
Hi, thank for your question
The port of the library to esp32 is in the plans, but not in the near future. A port for Raspberry RP2040 Pico will be released soon
Port to esp8266 is not planned because the platform limitations.

For ESP you can try other libraries
[Adafruit_Protomatter](https://github.com/adafruit/Adafruit_Protomatter)
[SmartMatrix](https://github.com/pixelmatix/SmartMatrix)
[PxMatrix](https://github.com/2dom/PxMatrix)
[ESP32-HUB75-MatrixPanel-I2S-DMA](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA)

**Comment by akshaythoke9116** [comment]
I want to use unicode with the library for P10 Display.
There is no sample code or guidance for using unicode in the all above libraries for P10 Display using ESP8266.
If possible guide me for it.

**Comment by board707** [comment]
Unfortunately, I can't offer any advice here. After all, I created this library exactly to solve problem with non-Latin characters in panel.
I don't know how to do it in other libraries.

**Comment by akshaythoke9116** [comment]
Ok thanks

**Comment by board707** [comment]
RP2040 board support added in version 0.9.0

**Comment by akshaythoke9116** [comment]
I have tried your library for P10 Display using STM32 but it is not working can you help in this case

**Comment by board707** [comment]
Please start new issue with detail explanation of the problem.
