### ISSUE TITLE
At starting ON condition display get noise

### ISSUE THREAD

**Issue by maxmurugan** [board707/DMD_STM32#134]
hi sir
how are you?

i am using pico same harware working fine red color and full color 

P4 RGB qiangli module DP5135D+RUL5158C   -- working fine no issue

**change new patch ic DP5125D+DP32020A  -- at initial time get noise after few minute automatically remove noise
how to remove noise ?**

both are working same setting ---      DMD_RGB_SHIFTREG_ABC <RGB80x40_S10_LNikon, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);

please help
![WhatsApp Image 2024-10-16 at 7 01 44 PM](https://github.com/user-attachments/assets/71f25582-cec5-4aec-a877-805bb21a6d50)

**Comment by maxmurugan** [comment]
DP5125+DP32020 only issue happened check video
hardware side fine

https://github.com/user-attachments/assets/4e572650-a273-4510-993b-39600933e54a

**Comment by board707** [comment]
Hi
Full initialization of all data in the code happens in less than a second... Also, your other matrix works... so I don't think the problem is in the code.
It looks more like some electronic transient processes. For example, charging a large capacitor in the power supply. Or a bad contact that heats up and turns on the circuit.

**Comment by maxmurugan** [comment]
hi sir

Issue happened ( DP5125+DP32020 )  this patch only
I try to change another 2 to 3 model working fine .

thanks for your support
